# This is a basic workflow to help you get started with Actions

name: Trigger Pushcut Notification

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0,15,30,45 10-20 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - shell: bash
      env:
        PUSHCUT_API_KEY: ${{ secrets.PUSHCUT_API_KEY }}
      run: |
        curl -X POST -H "Content-Type: application/json" -H 'API-Key: "$PUSHCUT_API_KEY"' -d '{"title": "Hello World", "text": "Hello World"}' https://api.pushcut.io/v1/notifications/Webhook
